obj-$(CONFIG_PONE_MODULE) += pone_mod.o

pone_mod-y += lf_order.o  pone_linux_adp.o pone_rmap.o pone_sys.o pone_init.o slice_state_adpter.o slice_state_process.o
pone_mod-y += chunk_block.o splitter.o splitter_adp.o slice_state_deamon.o page_reclaim_host.o timepoint.o

obj-$(CONFIG_PPR_MODULE) += ppr_mod.o

ppr_mod-y += page_reclaim_guest.o
